// Generated by GraphWalker (http://www.graphwalker.org)
package testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "testautomationsrc/main/resources/testautomation/grafica.graphml")
public interface grafica {

    @Edge()
    void inicializarServidor();

    @Edge()
    void borrar();

    @Vertex()
    void Inicio();

    @Edge()
    void buscar();

    @Edge()
    void agregar();

    @Vertex()
    void ServidorConContenidos();
}
